# Generated by Django 5.0.3 on 2024-03-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('class_location', models.CharField(choices=[('OFFLINE_AT_STUDENT_HOME', 'Offline at Student Home'), ('OFFLINE_AT_OWN_HOME', 'Offline at Own Home'), ('ONLINE', 'Online')], max_length=100)),
                ('full_address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('areas_covered', models.CharField(max_length=255)),
                ('time_slots_available', models.CharField(max_length=255)),
                ('total_experience', models.CharField(max_length=100)),
                ('certifications', models.TextField()),
                ('fees', models.CharField(max_length=100)),
                ('certificates_upload', models.FileField(upload_to='certificates/')),
                ('expertise_video_upload', models.FileField(upload_to='expertise_videos/')),
                ('profile_picture', models.FileField(upload_to='profile_pictures/')),
                ('insta_id', models.CharField(max_length=100)),
                ('fb_id', models.CharField(max_length=100)),
                ('kannada', models.CharField(choices=[('Mother Tongue', 'Kannada (Mother Tongue)'), ('Proficient', 'Kannada (Proficient)'), ('Basic', 'Kannada (Basic)')], max_length=20)),
                ('marathi', models.CharField(choices=[('Proficient', 'Marathi (Proficient)'), ('Basic', 'Marathi (Basic)')], max_length=20)),
                ('hindi', models.CharField(choices=[('Proficient', 'Hindi (Proficient)'), ('Basic', 'Hindi (Basic)')], max_length=20)),
                ('english', models.CharField(choices=[('Proficient', 'English (Proficient)'), ('Basic', 'English (Basic)')], max_length=20)),
                ('expert_category', models.CharField(choices=[('Fitness & Sports Experts', 'Fitness & Sports Experts'), ('Event Experts', 'Event Experts'), ('Music Experts', 'Music Experts'), ('Business Professionals', 'Business Professionals'), ('Lessons and Training', 'Lessons and Training'), ('Beauty', 'Beauty'), ('Others', 'Others')], max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.category')),
            ],
        ),
    ]
