# Generated by Django 5.0.3 on 2024-03-09 05:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='admin',
        ),
        migrations.AlterField(
            model_name='expert',
            name='alternate_phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian phone number.', regex='^\\+?91\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='emergency_phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian phone number.', regex='^\\+?91\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian phone number.', regex='^\\+?91\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='MasterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian phone number.', regex='^\\+?91\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expert_app.owner'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
