# Generated by Django 5.0.3 on 2024-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0002_remove_expert_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='subcategory',
            field=models.CharField(choices=[], default='default_value_here', max_length=100),
        ),
    ]
