# Generated by Django 5.0.3 on 2024-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0005_remove_expert_name_alter_expert_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='subcategory',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
