# Generated by Django 5.0.3 on 2024-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0006_alter_expert_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
