# Generated by Django 5.0.3 on 2024-03-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0008_alter_expert_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='owner',
        ),
    ]
