# Generated by Django 5.0.3 on 2024-03-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0010_expert_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.owner'),
        ),
    ]
