# Generated by Django 5.0.3 on 2024-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0018_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='english',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='kannada',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='marathi',
        ),
        migrations.AlterField(
            model_name='expert',
            name='languages_spoken',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('marathi', 'Marathi'), ('kannada', 'Kannada')], max_length=100),
        ),
    ]
