# Generated by Django 5.0.3 on 2024-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0021_alter_expert_class_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='certificates_upload',
        ),
        migrations.AlterField(
            model_name='expert',
            name='certifications',
            field=models.FileField(blank=True, upload_to='certificates/'),
        ),
    ]
