# Generated by Django 5.0.3 on 2024-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0022_remove_expert_certificates_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='certifications_upload',
            field=models.FileField(blank=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='certifications',
            field=models.TextField(),
        ),
    ]
