# Generated by Django 5.0.3 on 2024-04-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0024_alter_expert_certifications_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='languages_spoken',
            field=models.CharField(max_length=100),
        ),
    ]
