# Generated by Django 5.0.3 on 2024-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0025_alter_expert_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='class_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expert',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
